version: "3.9"

volumes:
  postgres_data:
  storage_data:

services:
  redis:
    restart: always
    image: "redis:alpine"

  db:
    restart: unless-stopped
    image: "postgres:alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: expressPG
    ports:
      - "4321:5432"
    env_file:
      - .env

  backend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/app/
    container_name: backend-node
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:supersecret@db:5432/expressPG?schema=public"
      NODE_ENV: development
    ports:
      - "3000:3000"
    restart: always
    

  # pg-admin:
  #   image: dpage/pgadmin4:7
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@demo.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=5500
  #   ports:
  #     - 'postgres:5500:5500'